stages:
  process_data:
    cmd: python src/data/make_dataset.py data/raw/Crop_Recommendation.csv
      data/processed
    deps:
      - src/data/make_dataset.py
      - data/raw/Crop_Recommendation.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
