name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t crop-classification-apis .

      - name: Pull data with DVC
        run: |
          pip install dvc[s3]
          dvc pull

      - name: Run Tests
        run: |
          docker run --rm crop-classification-apis pytest apis/test_api.py

      - name: Push Docker image
        run: |
          docker tag crop-classification ${{ secrets.DOCKER_USERNAME }}/crop-classification
          docker push ${{ secrets.DOCKER_USERNAME }}/crop-classification
